# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nhHackathon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire', '~> 4.8.2'
  pod 'Kingfisher', '~> 5.0'
  pod 'lottie-ios'
  # Pods for nhHackathon

  target 'nhHackathonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'nhHackathonUITests' do
    # Pods for testing
  end

end
